### ISSUE TITLE
Error MacOS npm start

### ISSUE THREAD

**Issue by Radicaly2k** [FredericHeem/starhackit#198]
Hi, I am getting this error doing npm start in the home directory

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ccontreras/Dev/NodeJS/starhackit-master/npm-debug.log
```
# 

And this in server folder

```
> starhackit-api@2.4.0 prestart /Users/ccontreras/Dev/NodeJS/starhackit-master/server
> npm run lint


> starhackit-api@2.4.0 lint /Users/ccontreras/Dev/NodeJS/starhackit-master/server
> eslint src

ENOENT: no such file or directory, lstat '/Users/ccontreras/Dev/NodeJS/starhackit-master/server/src/**'
Error: ENOENT: no such file or directory, lstat '/Users/ccontreras/Dev/NodeJS/starhackit-master/server/src/**'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.realpathSync (fs.js:1439:21)
    at /Users/ccontreras/Dev/NodeJS/starhackit-master/server/node_modules/eslint/lib/util/glob-util.js:159:24
    at Array.forEach (native)
    at Object.listFilesToProcess (/Users/ccontreras/Dev/NodeJS/starhackit-master/server/node_modules/eslint/lib/util/glob-util.js:153:18)
    at CLIEngine.executeOnFiles (/Users/ccontreras/Dev/NodeJS/starhackit-master/server/node_modules/eslint/lib/cli-engine.js:702:35)
    at Object.execute (/Users/ccontreras/Dev/NodeJS/starhackit-master/server/node_modules/eslint/lib/cli.js:174:107)
    at Object.<anonymous> (/Users/ccontreras/Dev/NodeJS/starhackit-master/server/node_modules/eslint/bin/eslint.js:76:28)
    at Module._compile (module.js:409:26)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! starhackit-api@2.4.0 lint: `eslint src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starhackit-api@2.4.0 lint script 'eslint src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the starhackit-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs starhackit-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls starhackit-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ccontreras/Dev/NodeJS/starhackit-master/server/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! starhackit-api@2.4.0 prestart: `npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starhackit-api@2.4.0 prestart script 'npm run lint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the starhackit-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs starhackit-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls starhackit-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ccontreras/Dev/NodeJS/starhackit-master/server/npm-debug.log
```

**Comment by FredericHeem** [comment]
The bug bit me too a few days ago, the current workaround is to `npm install` inside `server` as well  as in `client`.

**Comment by Radicaly2k** [comment]
Thanks for the help, it work well but when I start the server I get a lot of api-0 and also a failed status in the client.

**Comment by FredericHeem** [comment]
Any logs?

**Comment by Radicaly2k** [comment]
[client.txt](https://github.com/FredericHeem/starhackit/files/509669/client.txt)

[server.pdf](https://github.com/FredericHeem/starhackit/files/509664/server.pdf)

**Comment by FredericHeem** [comment]
Which version of npm are you using ? 
The server is working properly.

**Comment by Radicaly2k** [comment]
my version of npm is 2.15.9

**Comment by FredericHeem** [comment]
It should work fine with npm 3

**Comment by Radicaly2k** [comment]
Thanks will upgrade and will inform you the result.

**Comment by Radicaly2k** [comment]
ok, did what you said, left the server with the version 2.15.9 node v4.6.0 and the client I run it using nvm to change the node version to v5.0.0 and npm was 3.3.6 and it launched have to check now the dependencies as the MQ.

Thanks for your time.
