### ISSUE TITLE
HttpUtils] error name TypeError: Cannot read property 'publish' of undefined

### ISSUE THREAD

**Issue by Kav91** [FredericHeem/starhackit#38]
Just following the steps listed in the readme.
Can't seem to get the signup going with this error now.

Am I forgetting to do something?

Thanks

```
2016-01-23T10:33:34.207Z - debug: [koaServer] POST /api/v1/auth/register begins
2016-01-23T10:33:34.212Z - debug: [HttpUtils] respond
2016-01-23T10:33:34.216Z - debug: [AuthenticationApi] createPending:  username=theusername, password=123123, email=something@gmail.com
Executing (default): SELECT `id`, `username`, `email`, `firstName`, `lastName`, `facebookId`, `githubId`, `twitterId`, `googleId`, `password`, `passwordHash`, `createdAt`, `updatedAt` FROM `users` AS `User` WHERE `User`.`email` = 'something@gmail.com' LIMIT 1;
2016-01-23T10:33:34.225Z - info: [AuthenticationApi] createPending code  61i3wcY1N2fFhESS
Executing (default): INSERT INTO `user_pendings` (`id`,`username`,`email`,`password`,`passwordHash`,`code`,`updatedAt`,`createdAt`) VALUES (NULL,'theusername','something@gmail.com','','$2a$10$NTFDVjWRZoEOOkcjwZFaCutwzClPmKZpHOZUUxyY1u5nKSzco15.e','61i3wcY1N2fFhESS','2016-01-23 10:33:34.317 +00:00','2016-01-23 10:33:34.317 +00:00');
2016-01-23T10:33:34.324Z - info: [publisher] publish exchange:user, key:user.registering, message  {"code":"61i3wcY1N2fFhESS","username":"theusername","email":"something@gmail.com"}
2016-01-23T10:33:34.325Z - warn: [HttpUtils] error name TypeError: Cannot read property 'publish' of undefined
    at Publisher.publish$ (/Users/Kav91/.Trash/star/server/node_modules/rabbitmq-pubsub/build/publisher.js:109:74)
    at tryCatch (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at Publisher.publish (/Users/Kav91/.Trash/star/server/node_modules/rabbitmq-pubsub/build/publisher.js:105:40)
    at Object.createPending$ (/Users/Kav91/.Trash/star/server/build/plugins/users/authentication/AuthenticationApi.js:63:60)
    at tryCatch (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Kav91/.Trash/star/server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2016-01-23T10:33:34.327Z - debug: [koaServer] POST /api/v1/auth/register ends in 120ms
2016-01-23T10:33:34.329Z - debug: [koaServer] { request:
   { method: 'POST',
     url: '/api/v1/auth/register',
     header:
      { cookie: 'connect.sid=s%3AaZSsEi1jhTRFF5SXmu7B9L9dxmUho1bB.QOThGQV7J%2B4Niv6ifmFShMOUx1l3PHY1SQM9P5nTHuI',
        'accept-language': 'en-US,en;q=0.8',
        'accept-encoding': 'gzip, deflate',
        referer: 'http://localhost:8080/signup',
        'content-type': 'application/json',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36',
        origin: 'http://localhost:8080',
        accept: 'application/json',
        'content-length': '76',
        connection: 'close',
        host: 'localhost:8080' } },
  response:
   { status: 400,
     message: 'Bad Request',
     header: { 'content-type': 'application/json; charset=utf-8' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/api/v1/auth/register',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
```

**Comment by FredericHeem** [comment]
is `rabbitmq`configured properly in `server/config/default.json` ?

**Comment by Kav91** [comment]
Its default, so did. 
npm run devlabinstall
```Kavashens-MacBook-Pro:~ Kav91$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                   NAMES
c66a17ee4d27        rabbitmq:latest     "/docker-entrypoint.s"   2 minutes ago       Up 2 minutes        4369/tcp, 5671/tcp, 25672/tcp, 0.0.0.0:5672->5672/tcp   devlab_rabbitmq_kav91_1453713331482
```

Seems to be running fine.

Following with npm start 
Receive
App ending with error:  { [Error: connect ECONNREFUSED 127.0.0.1:5672]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672 }

What further do I configure in the default.json?
Just naturally assumed the default config. would be fine.

Currently can only see that the http port is different compared to the repo
```{
  "websiteUrl": "http://localhost:8080",
  "log": {
    "console": {
      "level": "debug",
      "timestamp": true,
      "colorize": true
    }
  },
  "rabbitmq": {
    "url":"amqp://localhost"
  },
  "frontend": {
    "path": "../client/build"
  },
  "http": {
    "port": 3000
  },
  "db":{
     // pg, sqlite3  etc ...
    "driver": "sqlite3",
    // postgres, sqlite
    "dialect":"sqlite",
    "database": "dev",
    "user": "user",
    "password": "password",
    "host": "localhost",
    "port": "5432",
    "logging": true,
    "storage": "./db.dev.sqlite"
  },
  "authentication":{
    /*
    "facebook":{
      "clientID":"",
      "clientSecret":"",
      "callbackURL": "http://localhost:3000/v1/auth/facebook/callback"
    }
    */
  },
  "mail": {
    /*
    "from": "StarHackIt <notification@starhack.it>",
    "signature": "The StarHackIt Team",
    "options": {
      "service": "Mailgun",
      "auth": {
        "user": "postmaster@yourproject.mailgun.org",
        "pass": "2109aef076a99216943a141d9abad454"
      }
    }
    */
  }
}

```

**Comment by Kav91** [comment]
Got it going! 
So opened up virtualbox, and added the port forwarding into the network configuration.

Thanks for pointing me in the right direction, appreciate it.
